# Generated by Django 5.0 on 2024-01-20 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRODUCTS', '0003_productscategoriemodel_and_more'),
        ('USERAPP', '0004_alter_adressmodel_adress_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('complete', models.BooleanField(default=False, null=True, verbose_name='Completed?')),
                ('transaction_id', models.CharField(max_length=200, null=True, verbose_name='Transaction Number')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('order_adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERAPP.adressmodel', verbose_name='Order Adress')),
            ],
            options={
                'verbose_name_plural': 'Orderses',
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantitiy')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PRODUCTS.productsmodel', verbose_name='Product')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ORDERS.ordermodel', verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'Order Products',
                'db_table': 'Order_Items',
            },
        ),
    ]
