# Generated by Django 5.0 on 2024-01-19 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0001_initial'),
        ('USERAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_title', models.CharField(max_length=50, verbose_name='Adress Title')),
                ('adress_city', models.CharField(max_length=100, verbose_name='City')),
                ('adress_description', models.TextField(max_length=1000, verbose_name='Adress Detials')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'Adresses',
                'db_table': 'Adress',
            },
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.productsmodel', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Basket',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.productsmodel', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Favorities',
                'db_table': 'Favorites',
            },
        ),
    ]
