# Generated by Django 5.0 on 2024-01-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0001_initial'),
        ('USERAPP', '0002_adressmodel_cardmodel_favoritemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardModel',
            new_name='CartModel',
        ),
        migrations.AddField(
            model_name='adressmodel',
            name='adress_district',
            field=models.CharField(max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='adressmodel',
            name='adress_neighborhood',
            field=models.CharField(max_length=50, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='adressmodel',
            name='adress_city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
    ]
