# Generated by Django 5.0 on 2024-01-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERAPP', '0003_rename_cardmodel_cartmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressmodel',
            name='adress_district',
            field=models.CharField(max_length=50, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='adressmodel',
            name='adress_neighborhood',
            field=models.CharField(max_length=50, verbose_name='Neighborhood'),
        ),
    ]
