# Generated by Django 5.0 on 2024-01-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_price', models.FloatField(verbose_name='Product Price')),
                ('product_description', models.TextField(max_length=500, verbose_name='Product Description')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Product Image')),
                ('product_shipping', models.BooleanField(blank=True, default=False, null=True, verbose_name='Free Cargo?')),
            ],
            options={
                'verbose_name_plural': 'Productses',
                'db_table': 'Products',
            },
        ),
    ]
