# Generated by Django 5.0 on 2024-01-19 12:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='', editable=True, populate_from='product_title', unique=True),
        ),
    ]
