# Generated by Django 5.0 on 2024-01-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0002_productsmodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategorieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_title', models.CharField(max_length=50, verbose_name='Categorie Name')),
                ('material_icon', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Product_Categorie',
            },
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='product_categorie',
            field=models.ManyToManyField(to='PRODUCTS.productscategoriemodel', verbose_name='Categorie'),
        ),
        migrations.CreateModel(
            name='ProductsCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Date')),
                ('comment_text', models.TextField(default=None, max_length=500, verbose_name='Comment')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PRODUCTS.productsmodel', verbose_name='Product Name')),
            ],
            options={
                'verbose_name_plural': 'Product Comments',
                'db_table': 'Comments',
            },
        ),
    ]
